name: '✏️ OSCP Season of Docs'
description: '通过开源社区的力量，共同打造更友好、更易上手的 AntV 文档 | Contribute to Ant Design Charts documentation with the power of open source community'
labels: ['OSCP']
projects: ['2025 AntV OSCP Season of Docs']
title: '[Docs]: '
body:
  - type: textarea
    id: 'summary'
    attributes:
      label: 任务介绍
      value: |
        > 此 ISSUE 为 [AntV 开源共建计划（AntV Open Source Contribution Plan，简称 AntV OSCP）Phase4 - 文档季](https://github.com/ant-design/ant-design-charts/issues/2936)的任务 ISSUE，欢迎社区开发者参与共建~
        >  - 更多任务，可查看 [GitHub Project - 2025 AntV OSCP Season of Docs](https://github.com/orgs/ant-design/projects/14)。

        > This ISSUE is one of the tasks of the [AntV Open Source Contribution Plan (referred to as AntV OSCP) Pharse4 - Season of Docs](https://github.com/ant-design/ant-design-charts/issues/2936) . Welcome to join us in building it together!
        > - For more tasks, you can check the [GitHub Project - 2025 AntV OSCP Season of Docs](https://github.com/orgs/ant-design/projects/14).

        ## 改造文档「xxx」

        ### 任务介绍

        - 任务名称：改造 [xxx](https://ant-design-charts.antgroup.com/components/xxx) 文档
        - 技术方向：Ant Design Charts / docs
        - 任务难度：新手友好 🌟 / 进阶 🌟🌟 / 专家 🌟🌟🌟
        - 可获得积分：20分 / 30分 / 50分

        ### 详细要求

        - 文档规范：
          - 参考示例：
            - [图表组件 - 折线图（Line）](https://ant-design-charts.antgroup.com/components/plots/line)
          - 文档结构：文档至少应该包括 **简介**、**代码演示**、**配置项**、**事件**、**方法**、**常见问题** 几个部分。
          - 文档内容：
            - 简介：简要介绍该图表的功能和特点。
            - 代码演示：尽可能多的覆盖该图表配置，展示如何使用该图表，示例代码统一放到 examples/[statistics|relations] 目录下，通过 Playground 引入即可。
            - 配置项：详细列出所有可配置的属性及其说明，参考 [G2](https://g2.antv.antgroup.com/)、[G6](https://g6.antv.antgroup.com/)。
            - 事件：列出该图表支持的事件及其触发条件（必要时补充添加核心代码）。
            - 方法：列出该图表支持的方法及其功能，已经在[图表方法](https://ant-design-charts.antgroup.com/components/plots/overview#%E5%9B%BE%E8%A1%A8%E6%96%B9%E6%B3%95)中的给跳转链接即可。
            - 常见问题（可选）：列出一些常见问题及其解决方案。
          - 注意事项：
            - 属性表格需要包含【属性】【描述】【类型】【默认值】【必选】列，所有的配置项包括绘图属性需要罗列完整。
            - 示例代码无需关心图表示例缩略图问题，后续统一上传。
            - 认领关系图的同学，需要将 `site/docs/components/graphs-demos` 中对应的示例先迁移到 `site/examples/relations` 目录下。

        ### 能力要求

        ```
        - 对 G2、G6 有一定了解，能阅读 Ant Design Charts 源码，编写示例。
        ```

        ### 执行路径

        #### 1. 认领任务

        选择感兴趣的且没有 Assignee 的任务，按格式回复，该任务 assign 给你后即为成功认领~
        - 认领回复格式：【@GitHub ID + Give it to me】
        - eg：【@interstellarmt Give it to me】

        #### 2. 做任务

        1. clone  charts 代码

        ```bash
        git clone https://github.com/ant-design/ant-design-charts.git
        ```

        2. 拉取所有线上分支

        ```bash
        git fetch
        ```

        3. 切换到 v2 分支

        ```bash
        git checkout v2
        ```

        4. 安装依赖

        ```bash
        pnpm install
        ```

        5. build lib

        ```bash
        pnpm run build:lib
        ```

        6. 本地启动 site 站点

        ```bash
        pnpm start
        ```

        7. 优化文档并预览效果

        - 对应文件位于 `site/docs/components/plots/xxx.zh.md` 和 `site/docs/components/graphs/xxx.zh.md`
        - 功能实现位于 `packages/xxx/xxx.ts`
        - 图表示例位于：`site/examples/xxx/xxx/demo`
        // - 图表示例暂无 欢迎补充👏


        #### 3. 提交 PR

        > 请保证文档语意通顺、格式正确、代码示例完整且能够正确编译，否则该 PR 将不会被 review 和 merge，此 issue 将被重新释放。

        1. 提交 Pull Request，等待 Code Review

        - PR 标题参考 `docs: 任务名称` ，如 `docs: 改造「图表组件 - 折线图（Line）」文档` ，并关联 `OSCP` 标签，以便快速进入 PR review 阶段。
        - PR 与对应任务 ISSUE 进行关联，方式：在 PR 正文中，通过 `- Fixed: #任务 ISSUE 号` 即可实现关联，eg：

        ![Image](https://github.com/user-attachments/assets/a05cc8f5-d42b-47fd-b3e2-be796a8b8017)

        2. 根据（多次） Code Review 建议修改

        3 等待合并入 v2 分支后，积分生效
