// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '/Users/liufu/publicWorkspace/ant-design-charts/packages/site/node_modules/@antv/dumi-theme-antv/dist/slots/Footer/index.js';
