// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/liufu/publicWorkspace/ant-design-charts/packages/site/node_modules/dumi/theme-default/slots/SearchBar/index.js';
export * from '/Users/liufu/publicWorkspace/ant-design-charts/packages/site/node_modules/dumi/theme-default/slots/SearchBar/index.js';
