"use strict";
/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */
/* auto-generated by NAPI-RS */
const { existsSync, readFileSync } = require('fs');
const { join } = require('path');
const { platform, arch } = process;
let nativeBinding = null;
let localFileExisted = false;
let loadError = null;
function isMusl() {
    // For Node 10
    if (!process.report || typeof process.report.getReport !== 'function') {
        try {
            const lddPath = require('child_process').execSync('which ldd').toString().trim();
            return readFileSync(lddPath, 'utf8').includes('musl');
        }
        catch (e) {
            return true;
        }
    }
    else {
        const { glibcVersionRuntime } = process.report.getReport().header;
        return !glibcVersionRuntime;
    }
}
switch (platform) {
    case 'android':
        switch (arch) {
            case 'arm64':
                localFileExisted = existsSync(join(__dirname, 'pack.android-arm64.node'));
                try {
                    if (localFileExisted) {
                        nativeBinding = require('./pack.android-arm64.node');
                    }
                    else {
                        nativeBinding = require('@utoo/pack-android-arm64');
                    }
                }
                catch (e) {
                    loadError = e;
                }
                break;
            case 'arm':
                localFileExisted = existsSync(join(__dirname, 'pack.android-arm-eabi.node'));
                try {
                    if (localFileExisted) {
                        nativeBinding = require('./pack.android-arm-eabi.node');
                    }
                    else {
                        nativeBinding = require('@utoo/pack-android-arm-eabi');
                    }
                }
                catch (e) {
                    loadError = e;
                }
                break;
            default:
                throw new Error(`Unsupported architecture on Android ${arch}`);
        }
        break;
    case 'win32':
        switch (arch) {
            case 'x64':
                localFileExisted = existsSync(join(__dirname, 'pack.win32-x64-msvc.node'));
                try {
                    if (localFileExisted) {
                        nativeBinding = require('./pack.win32-x64-msvc.node');
                    }
                    else {
                        nativeBinding = require('@utoo/pack-win32-x64-msvc');
                    }
                }
                catch (e) {
                    loadError = e;
                }
                break;
            case 'ia32':
                localFileExisted = existsSync(join(__dirname, 'pack.win32-ia32-msvc.node'));
                try {
                    if (localFileExisted) {
                        nativeBinding = require('./pack.win32-ia32-msvc.node');
                    }
                    else {
                        nativeBinding = require('@utoo/pack-win32-ia32-msvc');
                    }
                }
                catch (e) {
                    loadError = e;
                }
                break;
            case 'arm64':
                localFileExisted = existsSync(join(__dirname, 'pack.win32-arm64-msvc.node'));
                try {
                    if (localFileExisted) {
                        nativeBinding = require('./pack.win32-arm64-msvc.node');
                    }
                    else {
                        nativeBinding = require('@utoo/pack-win32-arm64-msvc');
                    }
                }
                catch (e) {
                    loadError = e;
                }
                break;
            default:
                throw new Error(`Unsupported architecture on Windows: ${arch}`);
        }
        break;
    case 'darwin':
        localFileExisted = existsSync(join(__dirname, 'pack.darwin-universal.node'));
        try {
            if (localFileExisted) {
                nativeBinding = require('./pack.darwin-universal.node');
            }
            else {
                nativeBinding = require('@utoo/pack-darwin-universal');
            }
            break;
        }
        catch (_a) { }
        switch (arch) {
            case 'x64':
                localFileExisted = existsSync(join(__dirname, 'pack.darwin-x64.node'));
                try {
                    if (localFileExisted) {
                        nativeBinding = require('./pack.darwin-x64.node');
                    }
                    else {
                        nativeBinding = require('@utoo/pack-darwin-x64');
                    }
                }
                catch (e) {
                    loadError = e;
                }
                break;
            case 'arm64':
                localFileExisted = existsSync(join(__dirname, 'pack.darwin-arm64.node'));
                try {
                    if (localFileExisted) {
                        nativeBinding = require('./pack.darwin-arm64.node');
                    }
                    else {
                        nativeBinding = require('@utoo/pack-darwin-arm64');
                    }
                }
                catch (e) {
                    loadError = e;
                }
                break;
            default:
                throw new Error(`Unsupported architecture on macOS: ${arch}`);
        }
        break;
    case 'freebsd':
        if (arch !== 'x64') {
            throw new Error(`Unsupported architecture on FreeBSD: ${arch}`);
        }
        localFileExisted = existsSync(join(__dirname, 'pack.freebsd-x64.node'));
        try {
            if (localFileExisted) {
                nativeBinding = require('./pack.freebsd-x64.node');
            }
            else {
                nativeBinding = require('@utoo/pack-freebsd-x64');
            }
        }
        catch (e) {
            loadError = e;
        }
        break;
    case 'linux':
        switch (arch) {
            case 'x64':
                if (isMusl()) {
                    localFileExisted = existsSync(join(__dirname, 'pack.linux-x64-musl.node'));
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./pack.linux-x64-musl.node');
                        }
                        else {
                            nativeBinding = require('@utoo/pack-linux-x64-musl');
                        }
                    }
                    catch (e) {
                        loadError = e;
                    }
                }
                else {
                    localFileExisted = existsSync(join(__dirname, 'pack.linux-x64-gnu.node'));
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./pack.linux-x64-gnu.node');
                        }
                        else {
                            nativeBinding = require('@utoo/pack-linux-x64-gnu');
                        }
                    }
                    catch (e) {
                        loadError = e;
                    }
                }
                break;
            case 'arm64':
                if (isMusl()) {
                    localFileExisted = existsSync(join(__dirname, 'pack.linux-arm64-musl.node'));
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./pack.linux-arm64-musl.node');
                        }
                        else {
                            nativeBinding = require('@utoo/pack-linux-arm64-musl');
                        }
                    }
                    catch (e) {
                        loadError = e;
                    }
                }
                else {
                    localFileExisted = existsSync(join(__dirname, 'pack.linux-arm64-gnu.node'));
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./pack.linux-arm64-gnu.node');
                        }
                        else {
                            nativeBinding = require('@utoo/pack-linux-arm64-gnu');
                        }
                    }
                    catch (e) {
                        loadError = e;
                    }
                }
                break;
            case 'arm':
                if (isMusl()) {
                    localFileExisted = existsSync(join(__dirname, 'pack.linux-arm-musleabihf.node'));
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./pack.linux-arm-musleabihf.node');
                        }
                        else {
                            nativeBinding = require('@utoo/pack-linux-arm-musleabihf');
                        }
                    }
                    catch (e) {
                        loadError = e;
                    }
                }
                else {
                    localFileExisted = existsSync(join(__dirname, 'pack.linux-arm-gnueabihf.node'));
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./pack.linux-arm-gnueabihf.node');
                        }
                        else {
                            nativeBinding = require('@utoo/pack-linux-arm-gnueabihf');
                        }
                    }
                    catch (e) {
                        loadError = e;
                    }
                }
                break;
            case 'riscv64':
                if (isMusl()) {
                    localFileExisted = existsSync(join(__dirname, 'pack.linux-riscv64-musl.node'));
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./pack.linux-riscv64-musl.node');
                        }
                        else {
                            nativeBinding = require('@utoo/pack-linux-riscv64-musl');
                        }
                    }
                    catch (e) {
                        loadError = e;
                    }
                }
                else {
                    localFileExisted = existsSync(join(__dirname, 'pack.linux-riscv64-gnu.node'));
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./pack.linux-riscv64-gnu.node');
                        }
                        else {
                            nativeBinding = require('@utoo/pack-linux-riscv64-gnu');
                        }
                    }
                    catch (e) {
                        loadError = e;
                    }
                }
                break;
            case 's390x':
                localFileExisted = existsSync(join(__dirname, 'pack.linux-s390x-gnu.node'));
                try {
                    if (localFileExisted) {
                        nativeBinding = require('./pack.linux-s390x-gnu.node');
                    }
                    else {
                        nativeBinding = require('@utoo/pack-linux-s390x-gnu');
                    }
                }
                catch (e) {
                    loadError = e;
                }
                break;
            default:
                throw new Error(`Unsupported architecture on Linux: ${arch}`);
        }
        break;
    default:
        throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`);
}
if (!nativeBinding) {
    if (loadError) {
        throw loadError;
    }
    throw new Error(`Failed to load native binding`);
}
const { registerWorkerScheduler, workerCreated, recvTaskMessageInWorker, sendTaskMessage, endpointWriteToDisk, endpointServerChangedSubscribe, endpointClientChangedSubscribe, projectNew, projectUpdate, projectOnExit, projectShutdown, projectWriteAllEntrypointsToDisk, projectEntrypointsSubscribe, projectHmrEvents, projectHmrIdentifiersSubscribe, projectUpdateInfoSubscribe, projectTraceSource, projectGetSourceForAsset, projectGetSourceMap, projectGetSourceMapSync, rootTaskDispose, initCustomTraceSubscriber, teardownTraceSubscriber } = nativeBinding;
module.exports.registerWorkerScheduler = registerWorkerScheduler;
module.exports.workerCreated = workerCreated;
module.exports.recvTaskMessageInWorker = recvTaskMessageInWorker;
module.exports.sendTaskMessage = sendTaskMessage;
module.exports.endpointWriteToDisk = endpointWriteToDisk;
module.exports.endpointServerChangedSubscribe = endpointServerChangedSubscribe;
module.exports.endpointClientChangedSubscribe = endpointClientChangedSubscribe;
module.exports.projectNew = projectNew;
module.exports.projectUpdate = projectUpdate;
module.exports.projectOnExit = projectOnExit;
module.exports.projectShutdown = projectShutdown;
module.exports.projectWriteAllEntrypointsToDisk = projectWriteAllEntrypointsToDisk;
module.exports.projectEntrypointsSubscribe = projectEntrypointsSubscribe;
module.exports.projectHmrEvents = projectHmrEvents;
module.exports.projectHmrIdentifiersSubscribe = projectHmrIdentifiersSubscribe;
module.exports.projectUpdateInfoSubscribe = projectUpdateInfoSubscribe;
module.exports.projectTraceSource = projectTraceSource;
module.exports.projectGetSourceForAsset = projectGetSourceForAsset;
module.exports.projectGetSourceMap = projectGetSourceMap;
module.exports.projectGetSourceMapSync = projectGetSourceMapSync;
module.exports.rootTaskDispose = rootTaskDispose;
module.exports.initCustomTraceSubscriber = initCustomTraceSubscriber;
module.exports.teardownTraceSubscriber = teardownTraceSubscriber;
