/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NodeRepr {
  append(newChild: NodeRepr): void
  appendChild(newChild: NodeRepr): NodeRepr
  removeChild(child: NodeRepr): NodeRepr
  prepend(newChild: NodeRepr): void
  after(newSibling: NodeRepr): void
  before(newSibling: NodeRepr): void
  insertBefore(newNode: NodeRepr, refNode?: NodeRepr | undefined | null): NodeRepr
  remove(): void
  setAttribute(name: string, value: string): void
  removeAttribute(name: string): void
  toggleAttribute(name: string, force?: boolean | undefined | null): boolean
  setAttributeNS(namespace: string | undefined | null, name: string, value: string): void
  removeAttributeNS(namespace: string | undefined | null, localName: string): void
  createElement(tagName: string): NodeRepr
  createTextNode(data: string): NodeRepr
  createComment(data: string): NodeRepr
  createDocumentFragment(): NodeRepr
  createProcessingInstruction(target: string, data: string): NodeRepr
  importNode(externalNode: NodeRepr, deep?: boolean | undefined | null): NodeRepr
  adoptNode(externalNode: NodeRepr): NodeRepr
  replaceChild(newChild: NodeRepr, oldChild: NodeRepr): NodeRepr
  replaceWith(newNode: NodeRepr): void
  get nodeType(): number
  get nodeName(): string
  get tagName(): string | null
  get namespaceURI(): string | null
  get prefix(): string | null
  get localName(): string | null
  get id(): string
  set id(id: string)
  get className(): string
  set className(className: string)
  get parentNode(): NodeRepr | null
  get firstChild(): NodeRepr | null
  get lastChild(): NodeRepr | null
  get previousSibling(): NodeRepr | null
  get nextSibling(): NodeRepr | null
  get parentElement(): NodeRepr | null
  get firstElementChild(): NodeRepr | null
  get lastElementChild(): NodeRepr | null
  get previousElementSibling(): NodeRepr | null
  get nextElementSibling(): NodeRepr | null
  get children(): Array<NodeRepr>
  get childElementCount(): number
  getRootNode(): NodeRepr
  get nodeValue(): string | null
  set nodeValue(value?: string | undefined | null)
  get target(): string | null
  get name(): string | null
  get publicId(): string | null
  get systemId(): string | null
  get doctype(): NodeRepr | null
  get data(): string | null
  set data(value: string)
  get textContent(): string
  set textContent(text: string)
  isSameNode(otherNode: NodeRepr): boolean
  get innerHTML(): string
  get length(): number
  set innerHTML(html: string)
  get outerHTML(): string
  set outerHTML(html: string)
  get ownerDocument(): NodeRepr | null
  toString(): string
  get childNodes(): Array<NodeRepr>
  _classListAdd(token: string): void
  _classListRemove(token: string): void
  _classListToggle(token: string, force?: boolean | undefined | null): boolean
  _classListContains(token: string): boolean
  _datasetGet(): Record<string, string>
  _datasetSet(key: string, value: string): void
  _datasetRemove(key: string): void
  substringData(offset: number, count: number): string
  appendData(data: string): void
  insertData(offset: number, data: string): void
  deleteData(offset: number, count: number): void
  replaceData(offset: number, count: number, data: string): void
  splitText(offset: number): NodeRepr | null
  insertAdjacentHTML(position: string, html: string): void
  insertAdjacentText(position: string, text: string): void
  insertAdjacentElement(position: string, element: NodeRepr): void
  normalize(): void
  lookupNamespaceURI(prefix?: string | undefined | null): string | null
  lookupPrefix(namespace: string): string | null
  compareDocumentPosition(other: NodeRepr): number
  select(selectors: string): NodeRepr | null
  selectAll(selectors: string): Array<NodeRepr>
  getAttribute(name: string): string | null
  getAttributeNames(): Array<string>
  hasAttributes(): boolean
  hasChildNodes(): boolean
  outerHtml(): string
  innerHtml(): string
  text(): string
  querySelector(selectors: string): NodeRepr | null
  querySelectorAll(selectors: string): Array<NodeRepr>
  hasAttribute(name: string): boolean
  getAttributeNS(namespace: string | undefined | null, localName: string): string | null
  hasAttributeNS(namespace: string | undefined | null, localName: string): boolean
  isDefaultNamespace(namespace?: string | undefined | null): boolean
  getElementById(id: string): NodeRepr | null
  getElementsByClassName(classNames: string): Array<NodeRepr>
  getElementsByTagName(tagName: string): Array<NodeRepr>
  contains(otherNode: NodeRepr): boolean
  isEqualNode(otherNode: NodeRepr): boolean
  get head(): NodeRepr | null
  get body(): NodeRepr | null
  get title(): string
  get documentElement(): NodeRepr | null
  matches(selectors: string): boolean
  closest(selectors: string): NodeRepr | null
  /** The node object, cann't be instantiated in javascript. So call the constructor will throw an error. */
  constructor(): void
  /** Clone this node to a new instance, not clone its descendants. */
  cloneSelfOnly(): NodeRepr
  /** Clone this node to a new instance, including its all descendants. */
  cloneRecursive(): NodeRepr
  cloneNode(deep?: boolean | undefined | null): NodeRepr
}

/** Parse string input to a html tree, return the root node. */
export declare function parse(html: string): NodeRepr
